---
- name: Install Apache
  package:
    name: "{{ apache_package }}"
    state: present

- name: Start Apache service
  service:
    name: apache2
    state: started
    enabled: yes

- name: Copy Apache configuration
  template:
    src: apache.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  # notify:
  #   - Restart Apache

- name: Enable mod_rewrite
  command: a2enmod rewrite
  when: ansible_os_family == "Debian"

- name: Enable site config
  command: a2ensite 000-default
  when: ansible_os_family == "Debian"

- name: Ensure default site is disabled
  command: a2dissite 000-default
  when: ansible_os_family != "Debian"

- name: Ensure the site is enabled
  command: systemctl start httpd
  when: ansible_os_family != "Debian"

- name: Restart Apache
  service:
    name: apache2
    state: restarted