- name: Проверить наличие маркерного файла
  ansible.builtin.stat:
    path: /path/to/marker/file
  register: mysql_marker_file

- name: Check if PyMySQL is installed
  command: python3 -c "import pymysql; print(pymysql.__version__)"
  register: pymysql_check
  ignore_errors: true

- name: Install PyMySQL
  pip:
    name: PyMySQL
    state: present
    executable: pip3
  when: pymysql_check.rc != 0  # Установка, только если команда завершилась с ошибкой

- name: Install MySQL server
  package:
    name: mysql-server
    state: present

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: true

- name: Set root user password
  mysql_user: 
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"
    state: present
    column_case_sensitive: false
  when: not mysql_marker_file.stat.exists

- name: copy .my.cnf file with root password credentials
  template: src=templates/root/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: Create WordPress database
  mysql_db:
    name: "{{ wordpress_db }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create WordPress user
  mysql_user:
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_password }}"
    state: present
    column_case_sensitive: false
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"