- name: Check if PyMySQL is installed
  command: python3 -c "import pymysql; print(pymysql.__version__)"
  register: pymysql_check
  ignore_errors: true

- name: Install PyMySQL
  pip:
    name: PyMySQL
    state: present
    executable: pip3
  when: pymysql_check.rc != 0  # Установка, только если команда завершилась с ошибкой

- name: Install MySQL server
  package:
    name: "{{ mysql_package }}"
    state: present

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: true

- name: Change root user password on first run
  mysql_user: login_user=root
              login_password=''
              name=root
              password={{ mysql_root_password }}
              priv=*.*:ALL,GRANT
              host={{ item }}
  with_items:
    - $ansible_hostname
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: true

- name: copy .my.cnf file with root password credentials
  template: src=templates/root/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: delete anonymous MySQL server user for $ansible_host
  action: mysql_user user="" host="{{ ansible_host }}" state="absent"

- name: delete anonymous MySQL server user for localhost
  action: mysql_user user="" state="absent"

- name: remove the MySQL test database
  action: mysql_db db=test state=absent

- name: Create WordPress database
  mysql_db:
    name: "{{ wordpress_db }}"
    state: present

- name: Create WordPress user
  mysql_user:
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_password }}"
    host: localhost
    state: present

- name: Grant privileges on WordPress database
  mysql_user:
    name: "{{ wordpress_db_user }}"
    database: "{{ wordpress_db }}"
    host: localhost
    privileges: all
    state: present

- name: Remove anonymous users
  mysql_user:
    name: ''
    host: localhost
    state: absent

- name: Disallow root login remotely
  mysql_user:
    name: root
    host: '{{ item }}'
    state: absent
  loop:
    - "{{ ansible_host }}"
    - '::1'

- name: Reload privilege tables
  command: mysqladmin -u root -p{{ mysql_root_password }} reload
