apiVersion: v1
kind: ServiceAccount
metadata:
  name: wordpress-diagnostics-sa
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wordpress-viewer
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wordpress-viewer-binding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: wordpress-diagnostics-sa
  namespace: dev
roleRef:
  kind: Role
  name: wordpress-viewer
  apiGroup: rbac.authorization.k8s.io