Vagrant.configure("2") do |config|

    # Базовые переменные
    base_box = "ubuntu/jammy64"
    base_box_version = "20241002.0.0"
    base_bridge = "eno1"
    path = "./sh_provision/"
    ip_ansible = "192.168.50.100"
    ip_dev = "192.168.50.200"
  
    # Конфигурация ВМ "dev"
    config.vm.define "dev" do |dev|
      dev.vm.box = base_box
      dev.vm.box_version = base_box_version
      dev.vm.box_check_update = false
      dev.vm.hostname = "dev"
      dev.vm.network "public_network", ip: ip_dev, bridge: base_bridge
      # dev.vm.network "forwarded_port", guest: 22, host: 2000
      dev.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "2048"
        end
      dev.vm.provision "file", source: "~/.ssh/vagrant_vm_rsa.pub", destination: "/home/vagrant/.ssh/vagrant_vm_rsa.pub"
      dev.vm.provision "shell", run: "always", path: "#{path}dev.sh"
    end
  
    # Конфигурация ВМ "ansible"
    config.vm.define "ansible" do |ansible|
      ansible.vm.box = base_box
      ansible.vm.box_version = base_box_version
      ansible.vm.box_check_update = false
      ansible.vm.hostname = "ansible"
      ansible.vm.network "public_network", ip: ip_ansible, bridge: base_bridge
      # ansible.vm.network "forwarded_port", guest: 22, host: 2300
      ansible.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "2048"
        end
    #   config.vm.synced_folder "./ansible/", "/home/vagrant/ansible/", type: "rsync"
    #   ansible.vm.synced_folder "./ansible/", "/home/vagrant/ansible/", type: "rsync"
      ansible.vm.synced_folder "./ansible/", "/home/vagrant/ansible/"
      ansible.vm.provision "file", source: "~/.ssh/vagrant_vm_rsa", destination: "/home/vagrant/.ssh/vagrant_vm_rsa"
      ansible.vm.provision "file", source: "~/.ssh/vagrant_vm_rsa.pub", destination: "/home/vagrant/.ssh/vagrant_vm_rsa.pub"
      ansible.vm.provision "shell", run: "always", path: "#{path}ansible.sh"
    end
  end