Vagrant.configure("2") do |config|
  
  # Базовые переменные
  base_box = "ubuntu/jammy64"
  base_box_version = "20241002.0.0"
  base_bridge = "eno1"
  path = "./sh_provision/"
  ip_store = "192.168.50.100"
  ip_server = "192.168.50.200"

   # Конфигурация ВМ "server"
   config.vm.define "server" do |server|
    server.vm.box = base_box
    server.vm.box_version = base_box_version
    server.vm.box_check_update = false
    server.vm.hostname = "server"
    server.ssh.forward_agent = true
    server.vm.network "public_network", ip: ip_server, bridge: base_bridge
    server.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "2048"
    end
    server.vm.provision "file", source: "~/.ssh/vagrant_vm_rsa.pub", destination: "/home/vagrant/.ssh/vagrant_vm_rsa.pub"
    server.vm.provision "shell", run: "always", path: "#{path}server.sh"
    # server.vm.provision "shell", run: "always", path: "#{path}crontab.sh"
  end

  # Конфигурация ВМ "store"
  config.vm.define "store" do |store|
    store.vm.box = base_box
    store.vm.box_version = base_box_version
    store.vm.box_check_update = false
    store.vm.hostname = "store"
    store.vm.network "public_network", ip: ip_store, bridge: base_bridge
    store.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "2048"
    end
    store.vm.provision "file", source: "~/.ssh/vagrant_vm_rsa", destination: "/home/vagrant/.ssh/vagrant_vm_rsa"
    store.vm.provision "file", source: "~/.ssh/vagrant_vm_rsa.pub", destination: "/home/vagrant/.ssh/vagrant_vm_rsa.pub"
    store.vm.provision "shell", run: "always", path: "#{path}store.sh"
  end
end