name: Diplom CI/CD for back-end

on:
  push:
    branches:
      - diplom
    paths:
      - "diplom/app/**"

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Copy .env.example to .env
        run: |
          cp diplom/.env.example diplom/.env

      - name: Build and run services
        run: |
          cd diplom  # Переход в директорию с docker-compose.yml
          docker-compose -f docker-compose.yml up -d --build

      - name: Shut down the services
        if: always()
        run: |
          cd diplom
          docker-compose -f docker-compose.yml down

      - name: Деплой на сервер
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          ssh -o StrictHostKeyChecking=no user@$SERVER_IP "cd /home/ubuntu/diplom/app && git pull && docker-compose up -d"
