name: Diplom CI/CD for front-end

on:
  push:
    branches:
      - diplom
    paths:
      - "diplom/frontend/**"

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка исходного кода
        uses: actions/checkout@v2

      - name: Установка Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Установка зависимостей
        run: |
          cd frontend
          npm install

      - name: Сборка и тестирование
        run: |
          cd frontend
          npm run build

      - name: Деплой на сервер
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          ssh -o StrictHostKeyChecking=no user@$SERVER_IP "cd /home/ubuntu/diplom/frontend && git pull && npm run deploy"
