name: CI/CD

on:
  push:
    branches:
      - diplom
    paths:
      - "diplom/app/**"
      - "diplom/frontend/**"

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'diplom/app/')
    steps:
      - name: Проверка исходного кода
        uses: actions/checkout@v2

      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Установка зависимостей
        run: |
          cd app
          pip install -r requirements.txt

      - name: Сборка и тестирование
        run: |
          cd app
          pytest  # Или команды для тестирования вашего приложения

      - name: Деплой на сервер
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          ssh -o StrictHostKeyChecking=no user@$SERVER_IP "cd /path/to/app && git pull && docker-compose up -d"

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'diplom/frontend/')
    steps:
      - name: Проверка исходного кода
        uses: actions/checkout@v2

      - name: Установка Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Установка зависимостей
        run: |
          cd frontend
          npm install

      - name: Сборка и тестирование
        run: |
          cd frontend
          npm run build  # Или команды для тестирования вашего приложения

      - name: Деплой на сервер
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          ssh -o StrictHostKeyChecking=no user@$SERVER_IP "cd /path/to/frontend && git pull && npm run deploy"
