name: CI/CD

on:
  push:
    branches:
      - diplom
    paths:
      - "diplom/app/**"
      - "diplom/frontend/**"

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка кода
        uses: actions/checkout@v2

      - name: Проверка на изменение путей
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            app:
              - 'diplom/app/**'
            frontend:
              - 'diplom/frontend/**'

  build-and-deploy-backend:
    runs-on: ubuntu-latest
    if: steps.changes.outputs.app == 'true'
    steps:
      - name: Проверка исходного кода
        uses: actions/checkout@v2

      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Установка зависимостей
        run: |
          cd app
          pip install -r requirements.txt

      - name: Сборка и тестирование
        run: |
          cd app
          pytest

      - name: Деплой на сервер
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          ssh -o StrictHostKeyChecking=no user@$SERVER_IP "cd /home/ubuntu/diplom/app && git pull && docker-compose up -d"

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    if: steps.changes.outputs.frontend == 'true'
    steps:
      - name: Проверка исходного кода
        uses: actions/checkout@v2

      - name: Установка Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Установка зависимостей
        run: |
          cd frontend
          npm install

      - name: Сборка и тестирование
        run: |
          cd frontend
          npm run build

      - name: Деплой на сервер
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          ssh -o StrictHostKeyChecking=no user@$SERVER_IP "cd /home/ubuntu/diplom/frontend && git pull && npm run deploy"
